export const ADD_TODO = 'ADD_TODO';
export const CHANGE_STATUS = 'CHANGE_STATUS';
export const DELETE_TODO = 'DELETE_TODO';
export const SHOW_ALL_ITEMS = 'SHOW_ALL_ITEMS';
export const SHOW_COMPLETED_ITEMS = 'SHOW_COMPLETED_ITEMS';
export const SHOW_ACTIVE_ITEMS = 'SHOW_ACTIVE_ITEMS';